// Auto-generated Gantt Master Data
export interface RawGanttRow {
  id: string;
  name: string;
  owner: string;
  type: "milestone" | "task" | "sub-task";
  parentId?: string | null;
  startOffset?: number | null;
  duration?: number | null;
  predecessorId?: string | null;
  lag?: number | null;
  isFixedAnchor?: boolean;
  endOffset?: number | null;
  startDate?: Date;
  endDate?: Date;
  status?: string;
  priority?: string;
  progressPercent?: number;
}

export const GANTT_MASTER_DATA: RawGanttRow[] = [
  {
    "id": "M1",
    "name": "Strategy & Master Manual",
    "owner": "Core (Abhinav & Aishwarya)",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T1",
    "name": "Master Manual Drafting",
    "owner": "Core",
    "type": "task",
    "parentId": "M1",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T1.S1",
    "name": "Draft v1: Core/Sponsorship/Marketing/Ops/Hospitality/Creative structure",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T1",
    "startOffset": -150,
    "endOffset": null,
    "duration": 4,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M1.T1.S2",
    "name": "Internal critique & expansion pass (gap analysis)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M1.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T1.S3",
    "name": "Add Registration Committee section",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M1.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T1.S4",
    "name": "Add Selection Framework (POC/Organiser/Volunteer criteria)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M1.T1.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T1.S5",
    "name": "Final formatting & visual design pass (v3)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M1.T1.S4",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T2",
    "name": "Selection Framework Design",
    "owner": "Core",
    "type": "task",
    "parentId": "M1",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T2.S1",
    "name": "Define eligibility gates for POC/Organiser/Volunteer",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M1.T1.S5",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T2.S2",
    "name": "Build scoring rubrics (100-pt scales per tier)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M1.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T2.S3",
    "name": "Document anti-bias & conflict-of-interest protocol",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M1.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T2.S4",
    "name": "Finalize appeal & transparency mechanism",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M1.T2.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T3",
    "name": "Budget Framework Lock",
    "owner": "Core - Finance",
    "type": "task",
    "parentId": "M1",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T3.S1",
    "name": "Build category-level budget template",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M1.T2.S4",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T3.S2",
    "name": "Set contingency reserve (10-15% of total)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M1.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M1.T3.S3",
    "name": "Circulate to Director/HOD for indicative approval",
    "owner": "",
    "type": "sub-task",
    "parentId": "M1.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M1.T3.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2",
    "name": "POC, Organiser & Volunteer Selection",
    "owner": "Core + All Committees",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T1",
    "name": "Recruitment Drive Launch",
    "owner": "Core",
    "type": "task",
    "parentId": "M2",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T1.S1",
    "name": "Publish Vertical POC & Event POC applications",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T1",
    "startOffset": -135,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M2.T1.S2",
    "name": "Publish Organiser applications (all 11 committees)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M2.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T1.S3",
    "name": "Open application window",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 10,
    "predecessorId": "M2.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T1.S4",
    "name": "Close applications (hard deadline)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M2.T1.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T2",
    "name": "Vertical & Event POC Selection",
    "owner": "Core",
    "type": "task",
    "parentId": "M2",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T2.S1",
    "name": "Blind scoring review by panel (anonymized rubric)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M2.T1.S4",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T2.S2",
    "name": "Shortlist top candidates per vertical",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M2.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T2.S3",
    "name": "Panel interviews",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M2.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T2.S4",
    "name": "Conflict-of-interest cross-check",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M2.T2.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T2.S5",
    "name": "Final POC announcements",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M2.T2.S4",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T3",
    "name": "Organiser Selection (11 Committees)",
    "owner": "Core + Committee POCs",
    "type": "task",
    "parentId": "M2",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T3.S1",
    "name": "Application screening against eligibility gates",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M2.T2.S5",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T3.S2",
    "name": "Scored shortlisting (100-pt rubric per committee)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M2.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T3.S3",
    "name": "Organiser interviews across all committees",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 4,
    "predecessorId": "M2.T3.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T3.S4",
    "name": "Diversity & balance review",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M2.T3.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T3.S5",
    "name": "Organiser confirmation & onboarding email",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M2.T3.S4",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T4",
    "name": "Volunteer Recruitment (Zone-based)",
    "owner": "Operations",
    "type": "task",
    "parentId": "M2",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T4.S1",
    "name": "Open volunteer registration (general pool)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 7,
    "predecessorId": "M2.T3.S5",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T4.S2",
    "name": "Zone-based lottery for oversubscribed zones",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M2.T4.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M2.T4.S3",
    "name": "Volunteer confirmation & WhatsApp group onboarding",
    "owner": "",
    "type": "sub-task",
    "parentId": "M2.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M2.T4.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3",
    "name": "Creative & Branding",
    "owner": "Creative & Decor Team",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T1",
    "name": "Theme Finalization",
    "owner": "Creative + Core",
    "type": "task",
    "parentId": "M3",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T1.S1",
    "name": "Present theme options to Core (Kings/Constellations/Time Travel)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T1",
    "startOffset": -120,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M3.T1.S2",
    "name": "Theme decision locked",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M3.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T1.S3",
    "name": "Build brand style guide (typography, icon set, palette)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M3.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T2",
    "name": "Digital Asset Production",
    "owner": "Creative",
    "type": "task",
    "parentId": "M3",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T2.S1",
    "name": "Social media post templates & LinkedIn headers",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M3.T1.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T2.S2",
    "name": "Digital rulebook templates",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M3.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T2.S3",
    "name": "Event intro video & motion graphics for backdrops",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M3.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T2.S4",
    "name": "Digital winner certificate templates",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M3.T2.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T3",
    "name": "Physical Asset Design & Print",
    "owner": "Creative",
    "type": "task",
    "parentId": "M3",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T3.S1",
    "name": "Design standees, banners, entrance arch, ID cards",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 4,
    "predecessorId": "M3.T2.S4",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T3.S2",
    "name": "Internal design review & Core brand sign-off (24h SLA)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M3.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T3.S3",
    "name": "Submit small-scale proofs to vendor (72-Hour Proofing Rule)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M3.T3.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T3.S4",
    "name": "Proof correction window (color/spelling/resolution)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M3.T3.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T3.S5",
    "name": "Final print production run",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M3.T3.S4",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M3.T3.S6",
    "name": "On-campus installation fabrication (photo booths, arches)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M3.T3",
    "startOffset": -2,
    "endOffset": null,
    "duration": 3,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M4",
    "name": "Marketing & Outreach",
    "owner": "Marketing Team",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T1",
    "name": "Target Institution Mapping",
    "owner": "Marketing - Outreach",
    "type": "task",
    "parentId": "M4",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T1.S1",
    "name": "Compile database of 60+ B-school contacts",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T1",
    "startOffset": -110,
    "endOffset": null,
    "duration": 6,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M4.T1.S2",
    "name": "Assign CL liaison owners per region",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M4.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T2",
    "name": "60-Day Content Calendar",
    "owner": "Marketing - Digital",
    "type": "task",
    "parentId": "M4",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T2.S1",
    "name": "Launch teaser videos & theme reveal posts",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T2",
    "startOffset": -60,
    "endOffset": null,
    "duration": 3,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M4.T2.S2",
    "name": "Vertical reveal & judge announcement content",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M4.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T2.S3",
    "name": "Countdown graphics cadence begins",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M4.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T3",
    "name": "CL Onboarding Kit Production",
    "owner": "Marketing",
    "type": "task",
    "parentId": "M4",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T3.S1",
    "name": "Draft CL kit (maps, hospitals, accommodation, schedule)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M4.T2.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T3.S2",
    "name": "Review with Hospitality & Operations for accuracy",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M4.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T3.S3",
    "name": "Finalize & distribute to confirmed CLs",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M4.T3.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T4",
    "name": "On-Campus Buzz Campaign",
    "owner": "Marketing - Promo",
    "type": "task",
    "parentId": "M4",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M4.T4.S1",
    "name": "Flash mobs & cafeteria stunts",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T4",
    "startOffset": -14,
    "endOffset": null,
    "duration": 5,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M4.T4.S2",
    "name": "Standee placement & final local awareness push",
    "owner": "",
    "type": "sub-task",
    "parentId": "M4.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M4.T4.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M5",
    "name": "Registration Committee Operations",
    "owner": "Registration Committee",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T1",
    "name": "Pre-Launch Setup",
    "owner": "Registration",
    "type": "task",
    "parentId": "M5",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T1.S1",
    "name": "Audit registration form fields & payment gateway link",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T1",
    "startOffset": -100,
    "endOffset": null,
    "duration": 2,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M5.T1.S2",
    "name": "Set up master tracker (applications, payments, records)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M5.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T1.S3",
    "name": "SOP briefing for Registration organisers",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M5.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T1.S4",
    "name": "Draft reminder & confirmation communication templates",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M5.T1.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T2",
    "name": "Active Registration Phase",
    "owner": "Registration",
    "type": "task",
    "parentId": "M5",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T2.S1",
    "name": "Forms go live",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M5.T1.S4",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T2.S2",
    "name": "Daily monitoring & duplicate/fraud flag checks",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 45,
    "predecessorId": "M5.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T2.S3",
    "name": "Payment verification cycles (SIB/UPI matching)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 45,
    "predecessorId": "M5.T1.S4",
    "lag": 0,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T2.S4",
    "name": "Weekly status reports to Core",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 45,
    "predecessorId": "M5.T1.S4",
    "lag": 0,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T3",
    "name": "Closing & Lock Phase",
    "owner": "Registration",
    "type": "task",
    "parentId": "M5",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T3.S1",
    "name": "Registration deadline (hard close)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T3",
    "startOffset": -14,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M5.T3.S2",
    "name": "Final payment reconciliation",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M5.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M5.T3.S3",
    "name": "Locked master list distributed (48h before fest)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T3",
    "startOffset": -2,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M5.T3.S4",
    "name": "Credential generation handover to Marketing",
    "owner": "",
    "type": "sub-task",
    "parentId": "M5.T3",
    "startOffset": -1,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M6",
    "name": "Sponsorship",
    "owner": "Sponsorship Team",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T1",
    "name": "Pitch Deck & Pipeline Setup",
    "owner": "Sponsorship",
    "type": "task",
    "parentId": "M6",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T1.S1",
    "name": "Build sponsorship pitch deck with Creative",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T1",
    "startOffset": -150,
    "endOffset": null,
    "duration": 3,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M6.T1.S2",
    "name": "Define sponsorship tiers & deliverables",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M6.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T1.S3",
    "name": "Set up centralized lead tracker",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M6.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T2",
    "name": "Corporate Pitching & MoUs",
    "owner": "Sponsorship",
    "type": "task",
    "parentId": "M6",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T2.S1",
    "name": "Active corporate pitching rounds",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 30,
    "predecessorId": "M6.T1.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T2.S2",
    "name": "MoU drafting & negotiation per sponsor",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 30,
    "predecessorId": "M6.T1.S3",
    "lag": 0,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T2.S3",
    "name": "MoU execution & 50% deposit collection",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M6.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T3",
    "name": "Payment Tranches & Deliverables",
    "owner": "Sponsorship",
    "type": "task",
    "parentId": "M6",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T3.S1",
    "name": "Collect 30% tranche (2 weeks before fest)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T3",
    "startOffset": -14,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M6.T3.S2",
    "name": "Branding asset handover to Creative for production",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M6.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T3.S3",
    "name": "In-kind/barter delivery physical inspection",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M6.T3.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T3.S4",
    "name": "VIP lounge & stall arrangement finalize",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M6.T3.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M6.T3.S5",
    "name": "Collect final 20% (morning of Day 1)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M6.T3",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M7",
    "name": "Academic Events (Core Sub-Unit)",
    "owner": "Core - Academic Events Wing",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T1",
    "name": "Rulebook & Rubric Design",
    "owner": "Core - Academic",
    "type": "task",
    "parentId": "M7",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T1.S1",
    "name": "Draft rulebooks for all 10+ verticals",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T1",
    "startOffset": -110,
    "endOffset": null,
    "duration": 8,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M7.T1.S2",
    "name": "Finalize objective rubric weightings per vertical",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M7.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T1.S3",
    "name": "Core sign-off on all rulebooks",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M7.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T2",
    "name": "Judge Sourcing",
    "owner": "Core - Academic",
    "type": "task",
    "parentId": "M7",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T2.S1",
    "name": "Identify & invite industry judges",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 10,
    "predecessorId": "M7.T1.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T2.S2",
    "name": "Confirm judge availability per vertical",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M7.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T2.S3",
    "name": "Build backup judge bench (min. 3/vertical)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M7.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T3",
    "name": "Case Study Security & Distribution",
    "owner": "Core - Academic",
    "type": "task",
    "parentId": "M7",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T3.S1",
    "name": "Finalize case studies/simulations with academic clubs",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M7.T2.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T3.S2",
    "name": "Set up time-locked digital distribution / sealed envelopes",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M7.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T4",
    "name": "Tabulation Architecture",
    "owner": "Core - Tabulation",
    "type": "task",
    "parentId": "M7",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T4.S1",
    "name": "Build master password-protected scoring sheet",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T4",
    "startOffset": -10,
    "endOffset": null,
    "duration": 3,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M7.T4.S2",
    "name": "Run mock data stress tests (extreme score cases)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M7.T4.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T4.S3",
    "name": "Dual-input protocol dry run (Abhinav & Aishwarya sheets)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M7.T4.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M7.T4.S4",
    "name": "Judge calibration session protocol finalized",
    "owner": "",
    "type": "sub-task",
    "parentId": "M7.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M7.T4.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8",
    "name": "Operations",
    "owner": "Operations Team",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T1",
    "name": "Venue Booking",
    "owner": "Operations",
    "type": "task",
    "parentId": "M8",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T1.S1",
    "name": "Submit Estate Office reservation forms",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T1",
    "startOffset": -90,
    "endOffset": null,
    "duration": 2,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M8.T1.S2",
    "name": "Confirm room & auditorium bookings",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 6,
    "predecessorId": "M8.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T2",
    "name": "Vendor Contracts (AV, Stage, LED)",
    "owner": "Operations",
    "type": "task",
    "parentId": "M8",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T2.S1",
    "name": "Source & vet technical vendors",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M8.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T2.S2",
    "name": "Negotiate contracts incl. delay penalty clauses",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M8.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T2.S3",
    "name": "Contracts signed",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M8.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T3",
    "name": "Logistics & Inventory Prep",
    "owner": "Operations",
    "type": "task",
    "parentId": "M8",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T3.S1",
    "name": "Procure stationery, cables, podiums, clickers",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 6,
    "predecessorId": "M8.T2.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T3.S2",
    "name": "Assemble Tech Backup Kits (per venue zone)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M8.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T3.S3",
    "name": "Rain Plan B rehearsal walkthrough",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M8.T3.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T4",
    "name": "Volunteer Deployment Planning",
    "owner": "Operations",
    "type": "task",
    "parentId": "M8",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T4.S1",
    "name": "Map volunteers to zones, gates, corridors",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T4",
    "startOffset": -10,
    "endOffset": null,
    "duration": 3,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M8.T4.S2",
    "name": "Print role cards & finalize escalation ladder",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M8.T4.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M8.T4.S3",
    "name": "Volunteer onboarding session (evening before fest)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M8.T4",
    "startOffset": -1,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M9",
    "name": "Hospitality",
    "owner": "Hospitality Team",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T1",
    "name": "Accommodation Sourcing",
    "owner": "Hospitality",
    "type": "task",
    "parentId": "M9",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T1.S1",
    "name": "Negotiate hotel corporate rates near campus",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T1",
    "startOffset": -80,
    "endOffset": null,
    "duration": 5,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M9.T1.S2",
    "name": "Confirm room blocks & shuttle schedules",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M9.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T2",
    "name": "Judge & Corporate Hospitality",
    "owner": "Hospitality",
    "type": "task",
    "parentId": "M9",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T2.S1",
    "name": "Collect judge profiles & travel details",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 6,
    "predecessorId": "M9.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T2.S2",
    "name": "Send personalized hospitality packages",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M9.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T2.S3",
    "name": "Assign student emissaries to judges",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M9.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T3",
    "name": "F&B Planning",
    "owner": "Hospitality",
    "type": "task",
    "parentId": "M9",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T3.S1",
    "name": "Menu engineering (VIP/competitor/volunteer tiers)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M9.T2.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T3.S2",
    "name": "Book catering vendors",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M9.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T4",
    "name": "Medical & First Aid Setup",
    "owner": "Hospitality",
    "type": "task",
    "parentId": "M9",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T4.S1",
    "name": "Arrange one first-aid kit & trained first-aider per floor",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T4",
    "startOffset": -5,
    "endOffset": null,
    "duration": 3,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M9.T4.S2",
    "name": "Coordinate emergency contact field with Registration form",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M9.T4.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M9.T4.S3",
    "name": "Brief first-aiders on escalation path to medical room/hospital",
    "owner": "",
    "type": "sub-task",
    "parentId": "M9.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M9.T4.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M10",
    "name": "Finance & Compliance",
    "owner": "Core - Finance & Compliance",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M10.T1",
    "name": "University Compliance",
    "owner": "Core - Finance",
    "type": "task",
    "parentId": "M10",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M10.T1.S1",
    "name": "Secure Director/HOD/Faculty sign-offs on dates & venue",
    "owner": "",
    "type": "sub-task",
    "parentId": "M10.T1",
    "startOffset": -150,
    "endOffset": null,
    "duration": 5,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M10.T1.S2",
    "name": "Configure SIB payment gateway with accounts dept.",
    "owner": "",
    "type": "sub-task",
    "parentId": "M10.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 5,
    "predecessorId": "M10.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M10.T2",
    "name": "Pre-Fest Financial Close",
    "owner": "Core - Finance",
    "type": "task",
    "parentId": "M10",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M10.T2.S1",
    "name": "Process vendor advance payouts",
    "owner": "",
    "type": "sub-task",
    "parentId": "M10.T2",
    "startOffset": -10,
    "endOffset": null,
    "duration": 3,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M10.T2.S2",
    "name": "Lock final operating budget & petty cash float",
    "owner": "",
    "type": "sub-task",
    "parentId": "M10.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M10.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M10.T2.S3",
    "name": "Confirm prize money escrow with accounts office",
    "owner": "",
    "type": "sub-task",
    "parentId": "M10.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M10.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M11",
    "name": "FEST DAYS — Nov 6 & 7, 2027",
    "owner": "All Teams",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M11.T1",
    "name": "Day 1 — Nov 6, 2027",
    "owner": "All Teams",
    "type": "task",
    "parentId": "M11",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M11.T1.S1",
    "name": "05:45 AM POC pre-briefing status dump (Google Form)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T1",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T1.S2",
    "name": "06:00 AM Core command briefing (all 10 POCs)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T1",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T1.S3",
    "name": "Venue unlock, AV checks, mic/projector tests",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T1",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T1.S4",
    "name": "Registration desks & sponsor stalls open",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T1",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T1.S5",
    "name": "Competition rounds running (all verticals)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T1",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T1.S6",
    "name": "Live score sheet collection & dual-input audit",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T1",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T1.S7",
    "name": "Day 1 results locked & handed to Marketing",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T1",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T1.S8",
    "name": "End-of-day POC feedback meeting (21:00-22:00)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T1",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T2",
    "name": "Day 2 — Nov 7, 2027",
    "owner": "All Teams",
    "type": "task",
    "parentId": "M11",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M11.T2.S1",
    "name": "06:00 AM Day 2 briefing & venue re-check",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 1,
    "predecessorId": "M11.T1.S8",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M11.T2.S2",
    "name": "Final rounds & flagship competition finals",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T2",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T2.S3",
    "name": "Valedictory ceremony & judge felicitation",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T2",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T2.S4",
    "name": "Winner announcement & prize disbursement kickoff",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T2",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M11.T2.S5",
    "name": "Campus restoration & vendor breakdown begins",
    "owner": "",
    "type": "sub-task",
    "parentId": "M11.T2",
    "startOffset": 0,
    "endOffset": null,
    "duration": 1,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M12",
    "name": "Post-Fest Closure",
    "owner": "Core + All Committees",
    "type": "milestone",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T1",
    "name": "Financial Audit & Reconciliation",
    "owner": "Core - Finance",
    "type": "task",
    "parentId": "M12",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T1.S1",
    "name": "Collect physical bills, cash memos, food tokens",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T1",
    "startOffset": 1,
    "endOffset": null,
    "duration": 3,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M12.T1.S2",
    "name": "Reconcile ledger against university account",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M12.T1.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T1.S3",
    "name": "Submit audited financial statement to management",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T1",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M12.T1.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T2",
    "name": "Prize & Honorarium Disbursement",
    "owner": "Core + Hospitality",
    "type": "task",
    "parentId": "M12",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T2.S1",
    "name": "Verify bank details, PAN cards, authorization letters",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M12.T1.S3",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T2.S2",
    "name": "Process prize transfers via accounts office",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M12.T2.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T2.S3",
    "name": "Dispatch judge honoraria",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T2",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M12.T2.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T3",
    "name": "Sponsor & Stakeholder Closure",
    "owner": "Sponsorship + Hospitality",
    "type": "task",
    "parentId": "M12",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T3.S1",
    "name": "Send sponsor proof-of-performance kits (7-day SLA)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T3",
    "startOffset": 2,
    "endOffset": null,
    "duration": 5,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M12.T3.S2",
    "name": "Send thank-you letters to judges (48h SLA)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M12.T3.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T3.S3",
    "name": "Collect outstanding sponsorship dues",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T3",
    "startOffset": null,
    "endOffset": null,
    "duration": 4,
    "predecessorId": "M12.T3.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T4",
    "name": "Media, Certificates & Aftermovie",
    "owner": "Marketing + Creative",
    "type": "task",
    "parentId": "M12",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T4.S1",
    "name": "Edit & publish official aftermovie (5-day SLA)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T4",
    "startOffset": 1,
    "endOffset": null,
    "duration": 5,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M12.T4.S2",
    "name": "Submit post-event press release",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M12.T4.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T4.S3",
    "name": "Generate & distribute certificates (10-day SLA)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T4",
    "startOffset": null,
    "endOffset": null,
    "duration": 8,
    "predecessorId": "M12.T4.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T5",
    "name": "Knowledge Transfer & Handoff",
    "owner": "Core",
    "type": "task",
    "parentId": "M12",
    "startOffset": null,
    "endOffset": null,
    "duration": null,
    "predecessorId": null,
    "lag": null,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T5.S1",
    "name": "Compile vendor & sponsor contact ratings",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T5",
    "startOffset": 5,
    "endOffset": null,
    "duration": 5,
    "predecessorId": null,
    "lag": 0,
    "isFixedAnchor": true
  },
  {
    "id": "M12.T5.S2",
    "name": "Document what failed & why (post-mortem)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T5",
    "startOffset": null,
    "endOffset": null,
    "duration": 3,
    "predecessorId": "M12.T5.S1",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T5.S3",
    "name": "Finalize reusable master tabulation template",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T5",
    "startOffset": null,
    "endOffset": null,
    "duration": 2,
    "predecessorId": "M12.T5.S2",
    "lag": 1,
    "isFixedAnchor": false
  },
  {
    "id": "M12.T5.S4",
    "name": "Submit Knowledge Transfer Document (30-day SLA)",
    "owner": "",
    "type": "sub-task",
    "parentId": "M12.T5",
    "startOffset": null,
    "endOffset": null,
    "duration": 15,
    "predecessorId": "M12.T5.S3",
    "lag": 1,
    "isFixedAnchor": false
  }
];
